on:
pull_request:
    branches:
      - main
push:
    branches:
      - main
      
name: "🚀 Release"
# action not working
jobs:
    release:
        name: 🚀 Release
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3.1.0
            - name: node
              uses: actions/setup-node@v3.5.0
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              run: dir
              working-directory: fast-structure
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} 
